import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { BoundaryObjectGeneratedModule, CrystalCoreLanguageGeneratedSharedModule } from './generated/module';
import { BoundaryObjectValidator, registerValidationChecks } from './boundary-object-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BoundaryObjectAddedServices = {
    validation: {
        BoundaryObjectValidator: BoundaryObjectValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BoundaryObjectServices = LangiumServices & BoundaryObjectAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const BoundaryObjectModule: Module<BoundaryObjectServices, PartialLangiumServices & BoundaryObjectAddedServices> = {
    validation: {
        BoundaryObjectValidator: () => new BoundaryObjectValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBoundaryObjectServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    BoundaryObject: BoundaryObjectServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CrystalCoreLanguageGeneratedSharedModule
    );
    const BoundaryObject = inject(
        createDefaultModule({ shared }),
        BoundaryObjectGeneratedModule,
        BoundaryObjectModule
    );
    shared.ServiceRegistry.register(BoundaryObject);
    registerValidationChecks(BoundaryObject);
    return { shared, BoundaryObject };
}
