import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { CrystalCoreLanguageGeneratedModule, CrystalCoreLanguageGeneratedSharedModule } from './generated/module';
import { CrystalCoreLanguageValidator, registerValidationChecks } from './crystal-core-language-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type CrystalCoreLanguageAddedServices = {
    validation: {
        CrystalCoreLanguageValidator: CrystalCoreLanguageValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type CrystalCoreLanguageServices = LangiumServices & CrystalCoreLanguageAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const CrystalCoreLanguageModule: Module<CrystalCoreLanguageServices, PartialLangiumServices & CrystalCoreLanguageAddedServices> = {
    validation: {
        CrystalCoreLanguageValidator: () => new CrystalCoreLanguageValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createCrystalCoreLanguageServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    CrystalCoreLanguage: CrystalCoreLanguageServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CrystalCoreLanguageGeneratedSharedModule
    );
    const CrystalCoreLanguage = inject(
        createDefaultModule({ shared }),
        CrystalCoreLanguageGeneratedModule,
        CrystalCoreLanguageModule
    );
    shared.ServiceRegistry.register(CrystalCoreLanguage);
    registerValidationChecks(CrystalCoreLanguage);
    return { shared, CrystalCoreLanguage };
}
